services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wgs
    ports:
      - 5432:5432

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_started
        required: true
    volumes:
      - ./uploads:/usr/water-and-gas-reading-system/uploads
    ports:
      - 80:80
